# LEARNING Nums 


In [11]:
import numpy as np

DECLARING ARRAY

In [12]:
list=(1,2,3)
a=np.array([list])
print(a)
b=np.array([1,2,3], dtype='int16')
print(b)

[[1 2 3]]
[1 2 3]


In [13]:
a.ndim #tells dimension of array

2

In [14]:
b.ndim

1

In [15]:
a.shape #(1,3) means 1 row, 2 columns 

(1, 3)

In [16]:
#to get data type meaning int8 int 32 etc
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('int16')

In [18]:
#to get size in bytes
b.itemsize

2

In [19]:
b.size #to get size of array

3

In [20]:
a.size

3

In [21]:
a.nbytes


12

# ACCESSING/CHANGING ELEMENTS SPECIFIC ELEMENTS ,ROWS AND COLUMNS ETC

In [22]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) #array of 2x7
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
#get shape 
a.shape

(2, 7)

In [24]:
a[1,5] #to get specifc elements 

13

In [25]:
a[1,-2] # we can use -ve index as well

13

In [26]:
#get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#similarly a column

In [28]:
#get more fnacy [start:end:stepsize]
a[0,0:6:1]

array([1, 2, 3, 4, 5, 6])

In [29]:
a[1,5]=20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [30]:
a[1,:]=0
print (a)

[[1 2 3 4 5 6 7]
 [0 0 0 0 0 0 0]]


In [31]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
b[0,1,1]

4

# INTIALIZING DIFFERENT TYPES OF ARRAYS

In [37]:
# ALL ZERO MATRIX
c=np.zeros([2,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
#for ones 
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
#any other no.
np.full([2,2],99)

array([[99, 99],
       [99, 99]])

In [42]:
#random decimal numbers
np.random.rand(4,2)

array([[0.43333618, 0.81915173],
       [0.25252547, 0.46360957],
       [0.21275387, 0.40665415],
       [0.43651835, 0.57994767]])

In [49]:
#random integers
np.random.randint(9,size=(3,3))

array([[0, 2, 2],
       [4, 6, 2],
       [2, 0, 1]])

In [51]:
#indentity 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
#repeat 
arr=np.array([[1,2,3]])
             
r=np.repeat(arr,3,0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


array copy karne ke liye 
a=b mat karna
a=b.copy se karna 
warna a main change karne se b main bhi change ho jaayega 


# MATHS


In [59]:
a=np.array([1,2,3,4])
print(a
     )

[1 2 3 4]


In [60]:
a+2

array([3, 4, 5, 6])

In [61]:
a-2

array([-1,  0,  1,  2])

In [62]:
a*2

array([2, 4, 6, 8])

In [63]:
a/2


array([0.5, 1. , 1.5, 2. ])

In [64]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [65]:
a**2

array([ 1,  4,  9, 16])

In [66]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [67]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# linear algebra


In [68]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [69]:
##to find det
c=np.identity(3)
np.linalg.det(c)

1.0

## stats

find mins and max

## REORGANIZED


In [74]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after= before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [76]:
#vertically stacking arrays
v1 = np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.stack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

use h stack for horizontal stack instead of vertical stack 

TO LOAD DATA FROM TEXT FILE



filedata= np.genfromtext('filename', delimiter=',')
filedata=filedata.astype('int32')



## Boolean data and masking

file data >50 
will give array with true at indices of values greater than 50 and false at less than 50

In [78]:
#you can use list to pass index in numpy